spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/promit_benefits
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
